sudo: required
services:
  - docker

before_install:
  - docker build -t mithungudipati/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mithungudipati/docker-react npm run test

deploy:
  provider: azure_web_apps
  username: AZURE_WA_USERNAME
  password: AZURE_WA_PASSWORD
  site: AZURE_WA_SITE
